language: php
php:
- 7.2
- 7.1
- 7.0
- 5.6
- 5.5
install:
- ant init
script: ant test
notifications:
  hipchat:
    rooms:
      secure: Ftqab466f6z+CIvcTokM9pfmuON9T+oFhUKi1eErw8CLZIxS7kWbjrPMzgAWMiQ10FvOFX2YFdTmVlO7gtjZ7dtdyiEC0EDby4RNK6hPvwWAv/YNhYfPwaiS9e+5l0kzK3Z8NZs0ELiQpC5LsLBM9f2Yo+opQPbn8erR9K41NMY=
